server:
  port: 8081
spring:
  application:
    name: delivery

  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/delivery
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
