server:
  port: 8080


spring:
  application:
    name: client
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/client
    password: ostentatious
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
