server:
  port: 8080

spring:
  application:
    name: client
  datasource:
    username: 'root'
    url: jdbc:postgresql://localhost:5432/client
    password: 'ostentatious'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'

